dist: bionic
language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: false
sudo: false
addons:
  apt:
    packages:
    - gir1.2-gtk-3.0                          # gi.repository.gtk
    - gobject-introspection                   # gobject-introspection-1.0
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall .
  - flake8 .
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
