language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
sudo: false
addons:
  apt:
    packages:
    - python3-gi                              # GObject
    - gir1.2-gtk-3.0                          # gi.repository.gtk
    - python3-xdg                             # PyXDG
install:
  - pip install -r requirements_travis.txt
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python -m compileall .
  - flake8 .
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
